//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ceng443-Hw1
//  @ File Name : AttackClosest.java
//  @ Date : 04.04.2015
//  @ Author : 
//
//




public class AttackClosest extends Strategy
{

    @Override
    public void act(Knight knight) {
        
        Knight closestKnight = null;
        double closestDistance = 0.0;
        double tempDistance = 0.0;
        
        if (knight.getTeam().getName().equalsIgnoreCase("EL MORAD")) 
        {
            closestKnight = Simulation.getInstance().getKarus().get(0);
            closestDistance = NeededFunctions.getInstance().calculateDistance(closestKnight, knight);
            
            
            for(Knight kn : Simulation.getInstance().getKarus())
            {
                tempDistance = NeededFunctions.getInstance().calculateDistance(kn, closestKnight);
                
                if(tempDistance <= closestDistance)
                    closestKnight = kn;
            }
                
        } 
        else if(knight.getTeam().getName().equalsIgnoreCase("KARUS")) 
        {
            closestKnight = Simulation.getInstance().getElMorads().get(0);
            closestDistance = NeededFunctions.getInstance().calculateDistance(closestKnight, knight);
            
            for(Knight kn : Simulation.getInstance().getElMorads())
            {
                tempDistance = NeededFunctions.getInstance().calculateDistance(kn, closestKnight);
                
                if(tempDistance <= closestDistance)
                    closestKnight = kn;
            }
        }
        
        double distanceX = closestKnight.getxPos() - knight.getxPos();
        double distanceY = closestKnight.getyPos() - knight.getyPos();
        
        if(knight.getxPos() < 770)
            knight.setxPos(knight.getxPos() +
                        distanceX / closestDistance * knight.getSpeed() / 35.0);
        
        
        if(50 < knight.getyPos() && knight.getyPos() < 500)
            knight.setyPos(knight.getyPos() +
                        distanceY / closestDistance * knight.getSpeed() / 35.0);
        
        
        
    }
}
