//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ceng443-Hw1
//  @ File Name : AttackWeakest.java
//  @ Date : 04.04.2015
//  @ Author : 
//
//




public class AttackWeakest extends Strategy
{

    @Override
    public void act(Knight knight) {
        
        Knight weakestKnight = null;
        
        if(knight.getTeam().getName().equalsIgnoreCase("EL MORAD"))
        {
            
            weakestKnight = Simulation.getInstance().getKarus().get(0);
            
            for(Knight kn : Simulation.getInstance().getKarus())
            {
                if(kn.getHealth() <= weakestKnight.getHealth())
                    weakestKnight = kn;
            }
            
        }
        else if(knight.getTeam().getName().equalsIgnoreCase("KARUS"))
        {
            weakestKnight = Simulation.getInstance().getElMorads().get(0);
            
            for(Knight kn : Simulation.getInstance().getElMorads())
            {
                if(kn.getHealth() <= weakestKnight.getHealth())
                    weakestKnight = kn;
            }
        }
    
        double distanceX = weakestKnight.getxPos() - knight.getxPos();
        double distanceY = weakestKnight.getyPos() - knight.getyPos();
        
        double distance = NeededFunctions.getInstance().calculateDistance(weakestKnight, knight);
        
        if(knight.getxPos() < 780)
            knight.setxPos(knight.getxPos() + 
                        distanceX / distance * knight.getSpeed() / 35.0);
        
        
        
        if(50 < knight.getyPos() && knight.getyPos() < 500)
            knight.setyPos(knight.getyPos() + 
                        distanceY / distance * knight.getSpeed() / 35.0);
            
        
    }
}
