
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.Timer;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ceng443-Hw1
//  @ File Name : BasicKnight.java
//  @ Date : 04.04.2015
//  @ Author : 
//
//




public class BasicKnight extends Knight
{

    public BasicKnight(double xPos, double yPos, Team team) {
        super(xPos, yPos, team);
    }
    
    @Override
    public void draw(Graphics g)
    {
        
    }
}
