
import java.awt.Graphics;
import java.util.Timer;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ceng443-Hw1
//  @ File Name : Grade1Decorator.java
//  @ Date : 04.04.2015
//  @ Author : 
//
//




public class Grade1Decorator extends KnightDecorator
{

    public Grade1Decorator(Knight otherKnight) {
        super(otherKnight);
    }

    @Override
    public void draw(Graphics g) {
        super.draw(g);
        
        if(decoratorKnight instanceof Priest)
        {
            NeededFunctions.getInstance().drawGradeDecorator(g, decoratorKnight.getxPos(), decoratorKnight.getyPos(), 7, 2);
            NeededFunctions.getInstance().drawGradeDecorator(g, decoratorKnight.getxPos() + 15, decoratorKnight.getyPos() + 33, 7, 2);            
            NeededFunctions.getInstance().drawGradeDecorator(g, decoratorKnight.getxPos() + 33, decoratorKnight.getyPos() + 1, 7, 2);            

        }
        else if(decoratorKnight instanceof Rogue)
        {
            NeededFunctions.getInstance().drawGradeDecorator(g, decoratorKnight.getxPos(), decoratorKnight.getyPos(), 12, 2);
            NeededFunctions.getInstance().drawGradeDecorator(g, decoratorKnight.getxPos() + 10, decoratorKnight.getyPos() + 22, 12, 2);        
            NeededFunctions.getInstance().drawGradeDecorator(g, decoratorKnight.getxPos() + 20, decoratorKnight.getyPos() , 12, 2);                
        }
        else if(decoratorKnight instanceof Mage)
        {
            NeededFunctions.getInstance().drawGradeDecorator(g, decoratorKnight.getxPos(), decoratorKnight.getyPos(), 12, 2);            
            NeededFunctions.getInstance().drawGradeDecorator(g, decoratorKnight.getxPos(), decoratorKnight.getyPos() + 20, 12, 2);        
            NeededFunctions.getInstance().drawGradeDecorator(g, decoratorKnight.getxPos() + 20, decoratorKnight.getyPos() , 12, 2);        
        }

    }
    
     
}
