
import java.awt.Graphics;
import java.util.Timer;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ceng443-Hw1
//  @ File Name : Grade3Decorator.java
//  @ Date : 04.04.2015
//  @ Author : 
//
//




public class Grade3Decorator extends KnightDecorator
{

    public Grade3Decorator(Knight otherKnight) {
        super(otherKnight);
    }

    @Override
    public void draw(Graphics g) {

        super.draw(g);
        
        
        if(decoratorKnight instanceof Priest)
        {
            NeededFunctions.getInstance().drawGradeDecorator(g, decoratorKnight.getxPos(), decoratorKnight.getyPos(), 7, 3);
        }
        else if(decoratorKnight instanceof Rogue)
        {
            NeededFunctions.getInstance().drawGradeDecorator(g, decoratorKnight.getxPos(), decoratorKnight.getyPos(), 12, 3);
        }
        else if(decoratorKnight instanceof Mage)
        {
            
            NeededFunctions.getInstance().drawGradeDecorator(g, decoratorKnight.getxPos(), decoratorKnight.getyPos(), 12, 3);            
        }
    
    }

    @Override
    public double getxPos() {
        return super.getxPos(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setxPos(double xPos) {
        super.setxPos(xPos); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public double getyPos() {
        return super.getyPos(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setyPos(double yPos) {
        super.setyPos(yPos); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getMaxHealth() {
        return super.getMaxHealth(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setMaxHealth(int maxHealth) {
        super.setMaxHealth(maxHealth); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getHealth() {
        return super.getHealth(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setHealth(int health) {
        super.setHealth(health); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getSpeed() {
        return super.getSpeed(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setSpeed(int speed) {
        super.setSpeed(speed); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Strategy getStrategy() {
        return super.getStrategy(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setStrategy(Strategy strategy) {
        super.setStrategy(strategy); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getScore() {
        return super.getScore(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setScore(int score) {
        super.setScore(score); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Team getTeam() {
        return super.getTeam(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setTeam(Team team) {
        super.setTeam(team); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void rangedAttack() {
        super.rangedAttack(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void meleeAttack() {
        super.meleeAttack(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void act() {
        super.act(); //To change body of generated methods, choose Tools | Templates.
    }
    
    
}
