
import java.awt.Graphics;
import java.util.Timer;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ceng443-Hw1
//  @ File Name : Grade3Decorator.java
//  @ Date : 04.04.2015
//  @ Author : 
//
//




public class Grade3Decorator extends KnightDecorator
{

    public Grade3Decorator(Knight otherKnight) {
        super(otherKnight);
    }

    @Override
    public void draw(Graphics g) {

        super.draw(g);
        
        
        if(decoratorKnight instanceof Priest)
        {
            NeededFunctions.getInstance().drawGradeDecorator(g, decoratorKnight.getxPos(), decoratorKnight.getyPos(), 7, 1);
        }
        else if(decoratorKnight instanceof Rogue)
        {
            NeededFunctions.getInstance().drawGradeDecorator(g, decoratorKnight.getxPos(), decoratorKnight.getyPos(), 12, 1);
        }
        else if(decoratorKnight instanceof Mage)
        {
            NeededFunctions.getInstance().drawGradeDecorator(g, decoratorKnight.getxPos(), decoratorKnight.getyPos(), 12, 1);            
        }
    
    }
}
