
import java.awt.Graphics;
import java.util.Timer;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ceng443-Hw1
//  @ File Name : Grade2Decorator.java
//  @ Date : 04.04.2015
//  @ Author : 
//
//




public class Grade2Decorator extends KnightDecorator
{

    public Grade2Decorator(int xPos, int yPos, Team team) {
        super(xPos, yPos, team);
    }

    @Override
    public void draw(Graphics g) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
