
import java.awt.Graphics;
import java.util.Timer;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ceng443-Hw1
//  @ File Name : Knight.java
//  @ Date : 04.04.2015
//  @ Author : 
//
//




public abstract class Knight
{
    private double xPos;
    private double yPos;
    private int hitPoint;
    private Timer coolDown;
    private int score;
    private int health;
    private int maxHealth;
    private int speed;
    private Team team;
    private Strategy strategy;
    private boolean isRangedAttack;

    public double getxPos() {
        return xPos;
    }

    public void setxPos(double xPos) {
        this.xPos = xPos;
    }

    public double getyPos() {
        return yPos;
    }

    public void setyPos(double yPos) {
        this.yPos = yPos;
    }

    public int getMaxHealth() {
        return maxHealth;
    }

    public void setMaxHealth(int maxHealth) {
        this.maxHealth = maxHealth;
    }

    public int getHealth() {
        return health;
    }

    public void setHealth(int health) {
        this.health = health;
    }

    public int getSpeed() {
        return speed;
    }

    public void setSpeed(int speed) {
        this.speed = speed;
    }

    public Strategy getStrategy() {
        return strategy;
    }

    public void setStrategy(Strategy strategy) {
        this.strategy = strategy;
    }

    public int getScore() {
        return score;
    }

    public void setScore(int score) {
        this.score = score;
    }

    public Team getTeam() {
        return team;
    }

    public void setTeam(Team team) {
        this.team = team;
    }

    public boolean getIsRangedAttack() {
        return isRangedAttack;
    }

    public void setIsRangedAttack(boolean isRangedAttack) {
        this.isRangedAttack = isRangedAttack;
    }
    
    
    
    public void rangedAttack()
    {
        
    } 
    
    
    public void meleeAttack()
    {
        
    }
    
    
    public abstract void draw(Graphics g);
    
//    public void applyDmg(Object int)
//    {
//    
//    }
    
    public void act(){
        this.strategy.act(this);
    }
    
    public Knight(double xPos, double yPos, Team team) {
        this.xPos = xPos;
        this.yPos = yPos;
        this.hitPoint = 0;
        this.coolDown = null;
        this.score = 0;
        this.health = 0;
        this.speed = 0;
        this.team = team;
        this.strategy = new RandomMove();
        this.isRangedAttack = false;
    }
    
    
}
