
import java.awt.Graphics;



//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ceng443-Hw1
//  @ File Name : KnightDecorator.java
//  @ Date : 04.04.2015
//  @ Author : 
//
//




public abstract class KnightDecorator extends Knight
{
    protected Knight decoratorKnight;

    public KnightDecorator(Knight otherKnight) {
        super(otherKnight.getxPos(), otherKnight.getyPos(), otherKnight.getTeam());
        this.decoratorKnight = otherKnight;
    }
    
    @Override
    public void draw(Graphics g)
    {
        decoratorKnight.draw(g);
    }
    
}
