

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ceng443-Hw1
//  @ File Name : KnightDecorator.java
//  @ Date : 04.04.2015
//  @ Author : 
//
//




public abstract class KnightDecorator extends Knight
{
    private BasicKnight decoratorKnight;

    public KnightDecorator(int xPos, int yPos, Team team) {
        super(xPos, yPos, team);
    }
}
