
import java.util.Random;
import java.util.Timer;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ceng443-Hw1
//  @ File Name : MageFactory.java
//  @ Date : 04.04.2015
//  @ Author : 
//
//




public class MageFactory extends SoldierFactory
{

    @Override
    public Knight produce(Team team) {
        
        Mage mage = null;
        
        Random rand = new Random();
        
        double random = (double) rand.nextInt(30);
        
        if(team.getName().equalsIgnoreCase("EL MORAD"))
        {
            mage = new Mage(NeededFunctions.getInstance().getFirstElMoradCoordinate().getX() + random, 
                            NeededFunctions.getInstance().getFirstElMoradCoordinate().getY() + random, 
                            team);
            
            Simulation.getInstance().getElMorads().add(mage);
        }
        else if(team.getName().equalsIgnoreCase("KARUS"))
        {
            mage = new Mage(NeededFunctions.getInstance().getFirstKarusCoordinate().getX() + random, 
                            NeededFunctions.getInstance().getFirstKarusCoordinate().getY() + random, 
                            team);
            
            Simulation.getInstance().getKarus().add(mage);
            
        }
//        Simulation.getInstance().getMageList().add(mage);
        
        
        
        return mage;
        
    }

    
}
