
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ceng443-Hw1
//  @ File Name : Priest.java
//  @ Date : 04.04.2015
//  @ Author : 
//
//




public class Priest extends BasicKnight
{

    public Priest(double xPos, double yPos, Team team) {
        super(xPos, yPos, team);
        this.setHealth(350);
        this.setSpeed(50);
        this.setTeam(team);
        this.setMaxHealth(350);
    }

    
    @Override
    public void rangedAttack()
    {
        int distance = 0;
        
        if(getTeam().getName().equalsIgnoreCase("EL MORAD"))
        {
            for(Knight kn : Simulation.getInstance().getElMorads())
            {
                distance = (int) NeededFunctions.getInstance().calculateDistance(this, kn);
                
                if(distance <= 100)
                {
                    setIsRangedAttack(true);

                    
                    if(kn.getHealth() <= kn.getMaxHealth() - 75)
                        kn.setHealth(kn.getHealth() + 75);
                    else
                        kn.setHealth(kn.getMaxHealth());
                }
                
            }
        }
        else if(getTeam().getName().equalsIgnoreCase("KARUS"))
        {
            for(Knight kn : Simulation.getInstance().getKarus())
            {
                distance = (int) NeededFunctions.getInstance().calculateDistance(this, kn);
                
                if(distance <= 100)
                {
                    setIsRangedAttack(true);
                    
                    if(kn.getHealth() <= kn.getMaxHealth() - 75)
                    {                        
                        kn.setHealth(kn.getHealth() + 75);
                    }
                    else
                    {
                        kn.setHealth(kn.getMaxHealth());
                    }
                }
            }
        }        
    }
    
    
    @Override
    public void meleeAttack()
    {
        int distance = 0;
        int index = -1;
        
        if(getTeam().getName().equalsIgnoreCase("EL MORAD"))
        {
            for(Knight kn : Simulation.getInstance().getKarus())
            {
                distance = (int) NeededFunctions.getInstance().calculateDistance(this, kn);
                if(distance <= 10)
                {
                    if(kn.getHealth() < 150)
                    {
                        
                        Simulation.getInstance().increaseTotalDamageOfTeam(Simulation.getTeamOfElMorad(), kn.getHealth());
                        Simulation.getInstance().increaseTotalKillOfTeam(Simulation.getTeamOfElMorad());
                        Simulation.getInstance().increaseScoreOfTeam(Simulation.getTeamOfElMorad());
                        
                        this.setScore(getScore() + 75);
                        
                        
                        
                        index = Simulation.getInstance().getKarus().indexOf(kn);
                        
                        
                    }
                    else
                    {
                        Simulation.getInstance().increaseTotalDamageOfTeam(Simulation.getTeamOfElMorad(), 150);
                        
                        kn.setHealth(kn.getHealth() - 150);
                    }
                    break;
                }
            }
            
            if(index != -1)
            {
                Simulation.getInstance().getKarus().get(index).setHealth(0);
                Simulation.getInstance().getKarus().remove(index);
                Simulation.getInstance().repaint();

            }
        }
        else if(getTeam().getName().equalsIgnoreCase("KARUS"))
        {
            for(Knight kn : Simulation.getInstance().getElMorads())
            {
                distance = (int) NeededFunctions.getInstance().calculateDistance(this, kn);
                if(distance <= 10)
                {
                    if(kn.getHealth() < 150)
                    {
                        
                        Simulation.getInstance().increaseTotalDamageOfTeam(Simulation.getTeamOfKarus(), kn.getHealth());
                        Simulation.getInstance().increaseTotalKillOfTeam(Simulation.getTeamOfKarus());
                        Simulation.getInstance().increaseScoreOfTeam(Simulation.getTeamOfKarus());
                        
                        
                        this.setScore(getScore() + 75);
                        
                        
                        
                        index = Simulation.getInstance().getElMorads().indexOf(kn);
                        
                    }
                    else
                    {
                        Simulation.getInstance().increaseTotalDamageOfTeam(Simulation.getTeamOfKarus(), 150);
                        
                        kn.setHealth(kn.getHealth() - 150);
                    }
                    break;
                }
            }
            if(index != -1)
            {
                Simulation.getInstance().getElMorads().get(index).setHealth(0);
                Simulation.getInstance().getElMorads().remove(index);
                Simulation.getInstance().repaint();
                
            }
        }
    }
    
    @Override
    public void draw(Graphics g) {
        
        Graphics2D g2d = (Graphics2D) g.create();

        
        g2d.setColor(this.getTeam().getColor());

        /*Draw and Fill Rectangle*/
        NeededFunctions.getInstance().drawAndFillPriest(g2d, getxPos(), getyPos(), 22, 22);
        /*Draw and Fill Rectangle*/

        /*Draw Centered Text*/
        NeededFunctions.getInstance().drawCenterText(g, getxPos() + 10, getyPos() + 10, 10f, "" + this.getHealth(), Color.WHITE);
        /*Draw Centered Text*/
        
        if(getIsRangedAttack() == true)
        {
            NeededFunctions.getInstance().drawRangedAttack(g, getxPos(), getyPos(), 0, "Priest");
            setIsRangedAttack(false);
        }
        
    }
}
