
import java.util.Random;



//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ceng443-Hw1
//  @ File Name : PriestFactory.java
//  @ Date : 04.04.2015
//  @ Author : 
//
//




public class PriestFactory extends SoldierFactory
{

    @Override
    public Knight produce(Team team) {
        
        Priest priest = null;
        
        Random rand = new Random();
        double random = (double) rand.nextInt(30);
        
        if(team.getName().equalsIgnoreCase("EL MORAD"))
        {
            priest = new Priest(NeededFunctions.getInstance().getFirstElMoradCoordinate().getX() + random,  
                                NeededFunctions.getInstance().getFirstElMoradCoordinate().getY() + random,  
                                team);
            
            Simulation.getInstance().getElMorads().add(priest);
        }
        else if(team.getName().equalsIgnoreCase("KARUS"))
        {
            priest = new Priest(NeededFunctions.getInstance().getFirstKarusCoordinate().getX() + random, 
                                NeededFunctions.getInstance().getFirstKarusCoordinate().getY() + random, 
                                team);
            
            Simulation.getInstance().getKarus().add(priest);
        }
//        Simulation.getInstance().getPriestList().add(priest);
        
        return priest;
    }
}
