
import java.util.Random;



//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ceng443-Hw1
//  @ File Name : Random.java
//  @ Date : 04.04.2015
//  @ Author : 
//
//




public class RandomMove extends Strategy
{

    @Override
    public void act(Knight knight) {        
        
        Random rand = new Random();
        int random1 = 397 + rand.nextInt(10);
        int random2 = 117 + rand.nextInt(10);
        
        double distanceX = random1 - knight.getxPos();
        double distanceY = random2 - knight.getyPos();
        
        double distance = (double) Math.sqrt(Math.pow(distanceX, 2) + Math.pow(distanceY, 2));
        
        
        if(knight.getxPos() < 780)
            knight.setxPos(knight.getxPos() + 
                        distanceX / distance * knight.getSpeed() / 35.0);
        else
            knight.setxPos(knight.getxPos());
        
        if(knight.getyPos() < 500)
            knight.setyPos(knight.getyPos() + 
                        distanceY / distance * knight.getSpeed() / 35.0);
        else
        {
            knight.setyPos(knight.getyPos());
        }
    
    }
}
