
import java.util.Random;
import java.util.Timer;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ceng443-Hw1
//  @ File Name : RogueFactory.java
//  @ Date : 04.04.2015
//  @ Author : 
//
//




public class RogueFactory extends SoldierFactory
{

    @Override
    public Knight produce(Team team) {

        Rogue rogue = null;
        
        Random rand = new Random();
        double random = (double) rand.nextInt(30);
        
        if(team.getName().equalsIgnoreCase("EL MORAD"))
        {
            
            
            rogue = new Rogue(NeededFunctions.getInstance().getFirstElMoradCoordinate().getX() + random, 
                              NeededFunctions.getInstance().getFirstElMoradCoordinate().getY() + random,
                              team);
            
            Simulation.getInstance().getElMorads().add(rogue);
        }
        else if(team.getName().equalsIgnoreCase("KARUS"))
        {
            rogue = new Rogue(NeededFunctions.getInstance().getFirstKarusCoordinate().getX() + random, 
                              NeededFunctions.getInstance().getFirstKarusCoordinate().getY() + random,
                              team);
         
            Simulation.getInstance().getKarus().add(rogue);
            
        }
        
//        Simulation.getInstance().getRogueList().add(rogue);
        
        return rogue;
        
    }

    
}
