
import java.util.Timer;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ceng443-Hw1
//  @ File Name : SoldierFactory.java
//  @ Date : 04.04.2015
//  @ Author : 
//
//




public abstract class SoldierFactory
{
    public abstract Knight produce(Team team);
}
