//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ceng443-Hw1
//  @ File Name : Strategy.java
//  @ Date : 04.04.2015
//  @ Author : 
//
//




public abstract class Strategy
{
    public abstract void act(Knight knight);
}
